version: '3.8'

services:
  db:
    image: docker.io/library/mysql:8.0
    container_name: spark-log-monitor-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: log_monitor
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
